// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: proto/video_games.proto

package video_games

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	utils "main/messages/utils"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Type int32

const (
	Type_GENERIC   Type = 0
	Type_SPORTS    Type = 1
	Type_ADVENTURE Type = 2
)

// Enum value maps for Type.
var (
	Type_name = map[int32]string{
		0: "GENERIC",
		1: "SPORTS",
		2: "ADVENTURE",
	}
	Type_value = map[string]int32{
		"GENERIC":   0,
		"SPORTS":    1,
		"ADVENTURE": 2,
	}
)

func (x Type) Enum() *Type {
	p := new(Type)
	*p = x
	return p
}

func (x Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Type) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_video_games_proto_enumTypes[0].Descriptor()
}

func (Type) Type() protoreflect.EnumType {
	return &file_proto_video_games_proto_enumTypes[0]
}

func (x Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Type.Descriptor instead.
func (Type) EnumDescriptor() ([]byte, []int) {
	return file_proto_video_games_proto_rawDescGZIP(), []int{0}
}

type Game struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Date            *utils.Date `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	DurationMinutes uint32      `protobuf:"varint,2,opt,name=duration_minutes,json=durationMinutes,proto3" json:"duration_minutes,omitempty"`
}

func (x *Game) Reset() {
	*x = Game{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_video_games_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Game) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Game) ProtoMessage() {}

func (x *Game) ProtoReflect() protoreflect.Message {
	mi := &file_proto_video_games_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Game.ProtoReflect.Descriptor instead.
func (*Game) Descriptor() ([]byte, []int) {
	return file_proto_video_games_proto_rawDescGZIP(), []int{0}
}

func (x *Game) GetDate() *utils.Date {
	if x != nil {
		return x.Date
	}
	return nil
}

func (x *Game) GetDurationMinutes() uint32 {
	if x != nil {
		return x.DurationMinutes
	}
	return 0
}

type VideoGame struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title          string      `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Type           []Type      `protobuf:"varint,2,rep,packed,name=type,proto3,enum=video_games.Type" json:"type,omitempty"`
	LibraryAddDate *utils.Date `protobuf:"bytes,3,opt,name=library_add_date,json=libraryAddDate,proto3" json:"library_add_date,omitempty"`
	Games          []*Game     `protobuf:"bytes,4,rep,name=games,proto3" json:"games,omitempty"`
	Favorite       bool        `protobuf:"varint,5,opt,name=favorite,proto3" json:"favorite,omitempty"`
}

func (x *VideoGame) Reset() {
	*x = VideoGame{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_video_games_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VideoGame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoGame) ProtoMessage() {}

func (x *VideoGame) ProtoReflect() protoreflect.Message {
	mi := &file_proto_video_games_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoGame.ProtoReflect.Descriptor instead.
func (*VideoGame) Descriptor() ([]byte, []int) {
	return file_proto_video_games_proto_rawDescGZIP(), []int{1}
}

func (x *VideoGame) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *VideoGame) GetType() []Type {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *VideoGame) GetLibraryAddDate() *utils.Date {
	if x != nil {
		return x.LibraryAddDate
	}
	return nil
}

func (x *VideoGame) GetGames() []*Game {
	if x != nil {
		return x.Games
	}
	return nil
}

func (x *VideoGame) GetFavorite() bool {
	if x != nil {
		return x.Favorite
	}
	return false
}

type Library struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*VideoGame `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *Library) Reset() {
	*x = Library{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_video_games_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Library) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Library) ProtoMessage() {}

func (x *Library) ProtoReflect() protoreflect.Message {
	mi := &file_proto_video_games_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Library.ProtoReflect.Descriptor instead.
func (*Library) Descriptor() ([]byte, []int) {
	return file_proto_video_games_proto_rawDescGZIP(), []int{2}
}

func (x *Library) GetList() []*VideoGame {
	if x != nil {
		return x.List
	}
	return nil
}

var File_proto_video_games_proto protoreflect.FileDescriptor

var file_proto_video_games_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x5f, 0x67, 0x61,
	0x6d, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x76, 0x69, 0x64, 0x65, 0x6f,
	0x5f, 0x67, 0x61, 0x6d, 0x65, 0x73, 0x1a, 0x11, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x75, 0x74,
	0x69, 0x6c, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x52, 0x0a, 0x04, 0x47, 0x61, 0x6d,
	0x65, 0x12, 0x1f, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0b, 0x2e, 0x75, 0x74, 0x69, 0x6c, 0x73, 0x2e, 0x44, 0x61, 0x74, 0x65, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x65, 0x12, 0x29, 0x0a, 0x10, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6d,
	0x69, 0x6e, 0x75, 0x74, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0f, 0x64, 0x75,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x69, 0x6e, 0x75, 0x74, 0x65, 0x73, 0x22, 0xc4, 0x01,
	0x0a, 0x09, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x47, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74,
	0x69, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c,
	0x65, 0x12, 0x25, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0e, 0x32,
	0x11, 0x2e, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x5f, 0x67, 0x61, 0x6d, 0x65, 0x73, 0x2e, 0x54, 0x79,
	0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x35, 0x0a, 0x10, 0x6c, 0x69, 0x62, 0x72,
	0x61, 0x72, 0x79, 0x5f, 0x61, 0x64, 0x64, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x75, 0x74, 0x69, 0x6c, 0x73, 0x2e, 0x44, 0x61, 0x74, 0x65, 0x52,
	0x0e, 0x6c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x79, 0x41, 0x64, 0x64, 0x44, 0x61, 0x74, 0x65, 0x12,
	0x27, 0x0a, 0x05, 0x67, 0x61, 0x6d, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11,
	0x2e, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x5f, 0x67, 0x61, 0x6d, 0x65, 0x73, 0x2e, 0x47, 0x61, 0x6d,
	0x65, 0x52, 0x05, 0x67, 0x61, 0x6d, 0x65, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x61, 0x76, 0x6f,
	0x72, 0x69, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x66, 0x61, 0x76, 0x6f,
	0x72, 0x69, 0x74, 0x65, 0x22, 0x35, 0x0a, 0x07, 0x4c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x79, 0x12,
	0x2a, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e,
	0x76, 0x69, 0x64, 0x65, 0x6f, 0x5f, 0x67, 0x61, 0x6d, 0x65, 0x73, 0x2e, 0x56, 0x69, 0x64, 0x65,
	0x6f, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x2a, 0x2e, 0x0a, 0x04, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x47, 0x45, 0x4e, 0x45, 0x52, 0x49, 0x43, 0x10, 0x00,
	0x12, 0x0a, 0x0a, 0x06, 0x53, 0x50, 0x4f, 0x52, 0x54, 0x53, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09,
	0x41, 0x44, 0x56, 0x45, 0x4e, 0x54, 0x55, 0x52, 0x45, 0x10, 0x02, 0x42, 0x1b, 0x5a, 0x19, 0x6d,
	0x61, 0x69, 0x6e, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2f, 0x76, 0x69, 0x64,
	0x65, 0x6f, 0x5f, 0x67, 0x61, 0x6d, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_video_games_proto_rawDescOnce sync.Once
	file_proto_video_games_proto_rawDescData = file_proto_video_games_proto_rawDesc
)

func file_proto_video_games_proto_rawDescGZIP() []byte {
	file_proto_video_games_proto_rawDescOnce.Do(func() {
		file_proto_video_games_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_video_games_proto_rawDescData)
	})
	return file_proto_video_games_proto_rawDescData
}

var file_proto_video_games_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_video_games_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_video_games_proto_goTypes = []interface{}{
	(Type)(0),          // 0: video_games.Type
	(*Game)(nil),       // 1: video_games.Game
	(*VideoGame)(nil),  // 2: video_games.VideoGame
	(*Library)(nil),    // 3: video_games.Library
	(*utils.Date)(nil), // 4: utils.Date
}
var file_proto_video_games_proto_depIdxs = []int32{
	4, // 0: video_games.Game.date:type_name -> utils.Date
	0, // 1: video_games.VideoGame.type:type_name -> video_games.Type
	4, // 2: video_games.VideoGame.library_add_date:type_name -> utils.Date
	1, // 3: video_games.VideoGame.games:type_name -> video_games.Game
	2, // 4: video_games.Library.list:type_name -> video_games.VideoGame
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_video_games_proto_init() }
func file_proto_video_games_proto_init() {
	if File_proto_video_games_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_video_games_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Game); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_video_games_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VideoGame); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_video_games_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Library); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_video_games_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_video_games_proto_goTypes,
		DependencyIndexes: file_proto_video_games_proto_depIdxs,
		EnumInfos:         file_proto_video_games_proto_enumTypes,
		MessageInfos:      file_proto_video_games_proto_msgTypes,
	}.Build()
	File_proto_video_games_proto = out.File
	file_proto_video_games_proto_rawDesc = nil
	file_proto_video_games_proto_goTypes = nil
	file_proto_video_games_proto_depIdxs = nil
}
